"""
ml_scorer.py — ML-Based Fraud Risk Inference Module
====================================================
Replaces the hand-written compute_risk_score() rule engine in main.py.
Loads the trained XGBoost model and runs inference on incoming transactions.

The feature engineering here MUST match exactly what train_model.py used.
"""

import json
import logging
import os

import joblib
import numpy as np

logger = logging.getLogger(__name__)

# ─── Globals (loaded once at startup) ────────────────────────────────────────
_model = None
_label_encoder_type = None
_feature_names: list[str] = []
_metadata: dict = {}

MODEL_PATH = os.path.join(os.path.dirname(__file__), "fraud_model.pkl")
META_PATH  = os.path.join(os.path.dirname(__file__), "model_metadata.json")

# Maps our mock_stream transaction types → PaySim types (what the model was trained on)
TRANSACTION_TYPE_MAP = {
    "P2P":          "TRANSFER",
    "Wire":         "TRANSFER",
    "Business":     "TRANSFER",
    "Payroll":      "CASH_OUT",
    "Bill Payment": "CASH_OUT",
    "TRANSFER":     "TRANSFER",
    "CASH_OUT":     "CASH_OUT",
}


def load_model() -> None:
    """
    Load the trained fraud model from disk.
    Must be called once at FastAPI startup before any predictions.
    """
    global _model, _label_encoder_type, _feature_names, _metadata

    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(
            f"Trained model not found at {MODEL_PATH}. "
            "Run: python train_model.py first."
        )

    artifact = joblib.load(MODEL_PATH)
    _model               = artifact["model"]
    _label_encoder_type  = artifact["label_encoder_type"]
    _feature_names       = artifact["feature_names"]

    if os.path.exists(META_PATH):
        with open(META_PATH) as f:
            _metadata = json.load(f)

    model_type = _metadata.get("model_type", "Unknown")
    roc_auc    = _metadata.get("test_roc_auc", "N/A")
    f1         = _metadata.get("test_f1", "N/A")
    logger.info(f"✅ ML fraud model loaded — {model_type} | ROC-AUC: {roc_auc} | F1: {f1}")


def _build_feature_vector(tx: dict) -> np.ndarray:
    """
    Translate a transaction dict into the feature vector the model expects.
    Uses the real PaySim-compatible balance fields generated by mock_stream.py.
    Must mirror train_model.py feature engineering exactly.
    """
    amount = float(tx.get("amount", 0))

    # --- Map transaction type → PaySim type → encoded integer ---
    raw_type    = tx.get("transaction_type", "TRANSFER")
    paysim_type = TRANSACTION_TYPE_MAP.get(raw_type, "TRANSFER")
    try:
        type_encoded = int(_label_encoder_type.transform([paysim_type])[0])
    except Exception:
        type_encoded = 1  # default to TRANSFER

    # --- Use REAL balance fields generated by mock_stream.py ---
    # These are now populated for every transaction, matching PaySim schema exactly.
    old_balance_org  = float(tx.get("oldbalanceOrg",  0.0))
    new_balance_orig = float(tx.get("newbalanceOrig", 0.0))
    old_balance_dest = float(tx.get("oldbalanceDest", 0.0))
    new_balance_dest = float(tx.get("newbalanceDest", 0.0))

    # Feature: balance change for sender (mirrors train_model.py)
    balance_diff_orig = new_balance_orig - old_balance_org

    # Feature: balance change for destination
    balance_diff_dest = new_balance_dest - old_balance_dest

    # Feature: was sender's account completely drained? (TOP signal: 57.9% importance)
    balance_zeroed = 1 if (new_balance_orig == 0.0 and old_balance_org > 0.0) else 0

    # Feature: was destination account empty before receiving money?
    dest_was_empty = 1 if (old_balance_dest == 0.0) else 0

    # Feature: ratio of amount to sender's prior balance (2nd signal: 34.6% importance)
    amount_to_balance_ratio = amount / (old_balance_org + 1.0)  # +1 avoids div/0

    # Feature: log-transform of amount (reduces right-skew, same as training)
    log_amount = float(np.log1p(amount))

    # Build vector in EXACT same column order as FEATURES list in train_model.py
    feature_vector = np.array([[
        log_amount,               # 1. log_amount
        type_encoded,             # 2. type_encoded
        balance_diff_orig,        # 3. balance_diff_orig
        balance_diff_dest,        # 4. balance_diff_dest
        balance_zeroed,           # 5. balance_zeroed        ← 57.9% importance
        dest_was_empty,           # 6. dest_was_empty
        amount_to_balance_ratio,  # 7. amount_to_balance_ratio ← 34.6% importance
    ]], dtype=float)

    return feature_vector


def predict_risk(tx: dict) -> tuple[int, str]:
    """
    Predict fraud risk for a transaction using the trained ML model.
    Returns (risk_score: int [0-100], risk_level: str ["Safe"|"Medium"|"Critical"])

    This is a drop-in replacement for main.py's compute_risk_score().
    """
    if _model is None:
        raise RuntimeError("ML model not loaded. Call load_model() first.")

    feature_vector = _build_feature_vector(tx)

    # Get fraud probability (index 1 = fraud class)
    fraud_proba = float(_model.predict_proba(feature_vector)[0][1])

    # Apply velocity and account-age boosting ON TOP of the ML score:
    # These are our domain-specific features PaySim didn't have —
    # they act as post-processing multipliers on the ML score.
    velocity     = int(tx.get("velocity_1hr", 0))
    account_age  = int(tx.get("time_since_account_creation_days", 999))

    boost = 0.0
    if velocity >= 15:
        boost += 0.12
    elif velocity >= 10:
        boost += 0.08
    elif velocity >= 5:
        boost += 0.04

    if account_age <= 7:
        boost += 0.10
    elif account_age <= 14:
        boost += 0.06
    elif account_age <= 30:
        boost += 0.03

    # Combine ML prediction with domain boost, cap at 1.0
    final_proba = min(fraud_proba + boost, 1.0)

    # Scale to 0-100
    risk_score = int(round(final_proba * 100))

    # Determine level using same thresholds as before
    if risk_score >= 70:
        risk_level = "Critical"
    elif risk_score >= 40:
        risk_level = "Medium"
    else:
        risk_level = "Safe"

    return risk_score, risk_level


def get_model_info() -> dict:
    """Return model metadata for the /health endpoint."""
    if not _metadata:
        return {"status": "not_loaded"}
    return {
        "model_type":      _metadata.get("model_type", "Unknown"),
        "roc_auc":         _metadata.get("test_roc_auc"),
        "f1_score":        _metadata.get("test_f1"),
        "precision":       _metadata.get("test_precision"),
        "recall":          _metadata.get("test_recall"),
        "feature_names":   _metadata.get("features", []),
        "feature_importance": _metadata.get("feature_importances", {}),
    }


def get_fired_explanation(tx: dict) -> list[str]:
    """
    Return human-readable explanation of what the model likely weighted.
    Used in the /score_risk endpoint to replace the old fired_rules list.
    """
    if _model is None:
        return ["Model not loaded"]

    feature_vector = _build_feature_vector(tx)
    fraud_proba    = float(_model.predict_proba(feature_vector)[0][1])
    importances    = _metadata.get("feature_importances", {})
    amount         = float(tx.get("amount", 0))
    velocity       = int(tx.get("velocity_1hr", 0))
    account_age    = int(tx.get("time_since_account_creation_days", 999))
    is_new_bene    = bool(tx.get("is_new_beneficiary", False))

    explanations = [
        f"ML Model fraud probability: {fraud_proba*100:.1f}%",
        f"Top signal — amount_to_balance_ratio (importance: {importances.get('amount_to_balance_ratio', 0):.3f})",
    ]

    if is_new_bene:
        explanations.append("New beneficiary detected — destination account had no prior balance")
    if velocity >= 10:
        explanations.append(f"High velocity: {velocity} transactions/hr — domain boost applied")
    if account_age <= 30:
        explanations.append(f"Young account: {account_age} days old — domain boost applied")
    if amount > 10000:
        explanations.append(f"Large transfer: ${amount:,.2f} — high log_amount signal")

    return explanations
